"""add priority and archive to goals

Revision ID: 32c7e082f778
Revises: 4062cdf958db
Create Date: 2026-01-19 15:32:34.194360+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32c7e082f778'
down_revision: Union[str, Sequence[str], None] = '4062cdf958db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goals', sa.Column('priority', sa.String(length=20), nullable=True))
    op.add_column('goals', sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=False))
    op.create_index('ix_goals_main_filter', 'goals', ['user_id', 'is_archived', 'status', 'priority'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_goals_main_filter', table_name='goals')
    op.drop_column('goals', 'is_archived')
    op.drop_column('goals', 'priority')
    # ### end Alembic commands ###
