"""Partishion tables

Revision ID: 4062cdf958db
Revises: a1b2c3d4e5f6
Create Date: 2026-01-17 12:14:22.569460+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4062cdf958db'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_goals_tags', 'goals', ['tags'], unique=False, postgresql_using='gin')
    op.add_column('outbox_events', sa.Column('trace_id', sa.String(length=255), nullable=True))
    op.add_column('outbox_events', sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('outbox_events', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('outbox_events', 'retry_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('outbox_events', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_index(op.f('ix_outbox_created_at'), table_name='outbox_events')
    op.create_index('ix_outbox_created_at_status', 'outbox_events', ['created_at', 'status'], unique=False)
    op.create_index('ix_outbox_processing', 'outbox_events', ['status', 'next_retry_at'], unique=False)
    op.create_index(op.f('ix_processed_goal_transactions_goal_id'), 'processed_goal_transactions', ['goal_id'], unique=False)
    op.drop_constraint(op.f('processed_goal_transactions_goal_id_fkey'), 'processed_goal_transactions', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('processed_goal_transactions_goal_id_fkey'), 'processed_goal_transactions', 'goals', ['goal_id'], ['goal_id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_processed_goal_transactions_goal_id'), table_name='processed_goal_transactions')
    op.drop_index('ix_outbox_processing', table_name='outbox_events')
    op.drop_index('ix_outbox_created_at_status', table_name='outbox_events')
    op.create_index(op.f('ix_outbox_created_at'), 'outbox_events', ['created_at'], unique=False)
    op.alter_column('outbox_events', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('outbox_events', 'retry_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('outbox_events', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('outbox_events', 'next_retry_at')
    op.drop_column('outbox_events', 'trace_id')
    op.drop_index('ix_goals_tags', table_name='goals', postgresql_using='gin')
    # ### end Alembic commands ###
