"""Add tags infinite goals fix structure

Revision ID: a1b2c3d4e5f6
Revises: ce616dc2eca4
Create Date: 2026-01-08 12:00:00.000000+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a1b2c3d4e5f6'
down_revision: Union[str, Sequence[str], None] = 'ce616dc2eca4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goals', sa.Column('tags', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False))
    op.alter_column('goals', 'finish_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.drop_column('goals', 'last_checked_date')
    op.create_table('goal_notifications',
        sa.Column('goal_id', sa.UUID(), nullable=False),
        sa.Column('last_checked_date', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['goal_id'], ['goals.goal_id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('goal_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('goal_notifications')
    op.add_column('goals', sa.Column('last_checked_date', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('goals', 'finish_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.drop_column('goals', 'tags')
    # ### end Alembic commands ###