"""Initial migration

Revision ID: f75028a1424d
Revises: 
Create Date: 2025-11-30 15:57:50.292296+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f75028a1424d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goals',
    sa.Column('goalId', sa.UUID(), nullable=False),
    sa.Column('userId', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('targetValue', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('currentValue', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('finishDate', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updatedAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lastCheckedDate', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('goalid')
    )
    op.create_index('ix_goals_status_finishDate', 'goals', ['status', 'finishDate'], unique=False)
    op.create_index('ix_goals_userId', 'goals', ['userId'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_goals_userId', table_name='goals')
    op.drop_index('ix_goals_status_finishDate', table_name='goals')
    op.drop_table('goals')
    # ### end Alembic commands ###
