"""Initial migration

Revision ID: f75028a1424d
Revises: 
Create Date: 2025-11-30 15:57:50.292296+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f75028a1424d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('target_value', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('current_value', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('finish_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_checked_date', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_goals_status_finish_date', 'goals', ['status', 'finish_date'], unique=False)
    op.create_index('ix_goals_user_id', 'goals', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_goals_user_id', table_name='goals')
    op.drop_index('ix_goals_status_finish_date', table_name='goals')
    op.drop_table('goals')
    # ### end Alembic commands ###
