"""Correct migration version

Revision ID: 46554423ab4e
Revises: 
Create Date: 2025-12-18 08:12:13.720434+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46554423ab4e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('userId', sa.UUID(), nullable=False),
    sa.Column('role', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('passwordHash', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('isActive', sa.Boolean(), nullable=True),
    sa.Column('lastLogin', sa.DateTime(timezone=True), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('userId'),
    sa.UniqueConstraint('email', name='uq_users_email')
    )
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_table('sessions',
    sa.Column('sessionId', sa.UUID(), nullable=False),
    sa.Column('userId', sa.UUID(), nullable=False),
    sa.Column('userAgent', sa.String(), nullable=False),
    sa.Column('deviceName', sa.String(), nullable=False),
    sa.Column('ip', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=True),
    sa.Column('refreshFingerprint', sa.String(), nullable=False),
    sa.Column('expiresAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['users.userId'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('sessionId')
    )
    op.create_index('ix_sessions_expires_at', 'sessions', ['expiresAt'], unique=False)
    op.create_index('ix_sessions_fingerprint', 'sessions', ['refreshFingerprint'], unique=False)
    op.create_index('ix_sessions_user_id', 'sessions', ['userId'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sessions_user_id', table_name='sessions')
    op.drop_index('ix_sessions_fingerprint', table_name='sessions')
    op.drop_index('ix_sessions_expires_at', table_name='sessions')
    op.drop_table('sessions')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
