"""Create new table and index for them

Revision ID: 6e3c18cec58f
Revises: 45e903802241
Create Date: 2025-11-13 08:59:31.018775+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6e3c18cec58f'
down_revision: Union[str, Sequence[str], None] = '45e903802241'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_datasets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('version', sa.String(length=100), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'BUILDING', 'READY', 'FAILED', name='training_dataset_status_enum'), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version')
    )
    op.create_index('ix_training_datasets_status_created', 'training_datasets', ['created_at', 'status'], unique=False, postgresql_where=False)
    op.create_index('ix_training_datasets_version', 'training_datasets', ['version'], unique=True)
    op.create_index('ix_categories_name', 'categories', ['name'], unique=False)
    op.add_column('classification_results', sa.Column('merchant', sa.String(length=255), nullable=True))
    op.add_column('classification_results', sa.Column('description', sa.String(), nullable=True))
    op.add_column('classification_results', sa.Column('mcc', sa.Integer(), nullable=True))
    op.alter_column('classification_results', 'confidence',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
    op.create_index('ix_classification_results_source', 'classification_results', ['source'], unique=False)
    op.create_index('ix_feedback_processed', 'feedback', ['processed'], unique=False)
    op.create_index('ix_feedback_transaction_id', 'feedback', ['transaction_id'], unique=False)
    op.add_column('models', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.create_index('ix_models_active', 'models', ['is_active'], unique=True, postgresql_where=False)
    op.create_index('ix_models_created_at', 'models', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index('ix_models_version', 'models', ['version'], unique=True)
    op.create_index('ix_rules_category_id', 'rules', ['category_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_rules_category_id', table_name='rules')
    op.drop_index('ix_models_version', table_name='models')
    op.drop_index('ix_models_created_at', table_name='models')
    op.drop_index('ix_models_active', table_name='models', postgresql_where=False)
    op.drop_column('models', 'is_active')
    op.drop_index('ix_feedback_transaction_id', table_name='feedback')
    op.drop_index('ix_feedback_processed', table_name='feedback')
    op.drop_index('ix_classification_results_source', table_name='classification_results')
    op.alter_column('classification_results', 'confidence',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('classification_results', 'mcc')
    op.drop_column('classification_results', 'description')
    op.drop_column('classification_results', 'merchant')
    op.drop_index('ix_categories_name', table_name='categories')
    op.drop_index('ix_training_datasets_version', table_name='training_datasets')
    op.drop_index('ix_training_datasets_status_created', table_name='training_datasets', postgresql_where=False)
    op.drop_table('training_datasets')
    # ### end Alembic commands ###
