"""Correct migration version

Revision ID: 3965c5157790
Revises: 8bd009546353
Create Date: 2025-12-23 08:12:06.754471+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3965c5157790'
down_revision: Union[str, Sequence[str], None] = '8bd009546353'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outbox_events',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('topic', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=255), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('last_error', sa.String(length=512), nullable=True),
    sa.CheckConstraint('retry_count >= 0', name='ck_retry_count_non_negative'),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index('ix_outbox_status_created_at', 'outbox_events', ['status', 'created_at'], unique=False)
    op.alter_column('categories', 'keywords',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=False)
    op.drop_constraint(op.f('uq_classification_results_transaction_id'), 'classification_results', type_='unique')
    op.drop_index(op.f('ix_models_created_at'), table_name='models')
    op.create_index('ix_models_created_at', 'models', [sa.literal_column('created_at DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_models_created_at', table_name='models')
    op.create_index(op.f('ix_models_created_at'), 'models', ['created_at'], unique=False)
    op.create_unique_constraint(op.f('uq_classification_results_transaction_id'), 'classification_results', ['transaction_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('categories', 'keywords',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=True)
    op.drop_index('ix_outbox_status_created_at', table_name='outbox_events')
    op.drop_table('outbox_events')
    # ### end Alembic commands ###
