"""Correct migration version

Revision ID: 03965c515779001
Revises: 8bd009546353
Create Date: 2025-12-23 08:12:06.754471+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '03965c515779001'
down_revision: Union[str, Sequence[str], None] = "8bd009546353"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE classification_source_enum AS ENUM ('RULES', 'ML', 'MANUAL')")
    op.execute("CREATE TYPE rule_pattern_type_enum AS ENUM ('REGEX', 'CONTAINS', 'MCC', 'EXACT')")
    op.execute("CREATE TYPE training_dataset_status_enum AS ENUM ('PENDING', 'BUILDING', 'READY', 'FAILED')")
    op.create_table('categories',
        sa.Column('category_id', sa.Integer(), autoincrement=False, nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('description', sa.String(length=1024), nullable=True),
        sa.Column('keywords', sa.ARRAY(sa.String()), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('category_id'),
        sa.UniqueConstraint('name')
    )
    op.create_index('ix_categories_keywords_gin', 'categories', ['keywords'], unique=False, postgresql_using='gin')
    op.create_index('ix_categories_name', 'categories', ['name'], unique=False)
    op.create_table('models',
        sa.Column('model_id', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('version', sa.String(length=100), nullable=False),
        sa.Column('path', sa.String(length=1024), nullable=False),
        sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint('model_id')
    )
    op.create_index('ix_models_active_unique', 'models', ['is_active'], unique=True, postgresql_where=sa.text('is_active IS true'))
    op.create_index('ix_models_created_at', 'models', [sa.text('created_at DESC')], unique=False)
    op.create_index('ix_models_version', 'models', ['version'], unique=True)
    op.create_table('rules',
        sa.Column('rule_id', sa.UUID(), nullable=False),
        sa.Column('category_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('pattern', sa.String(), nullable=False),
        sa.Column('pattern_type', postgresql.ENUM('REGEX', 'CONTAINS', 'MCC', 'EXACT', name='rule_pattern_type_enum', create_type=False), nullable=False),
        sa.Column('mcc', sa.Integer(), nullable=True),
        sa.Column('priority', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.CheckConstraint('priority >= 1 AND priority <= 999', name='ck_rule_priority_range'),
        sa.ForeignKeyConstraint(['category_id'], ['categories.category_id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('rule_id')
    )
    op.create_index('ix_rules_category_id', 'rules', ['category_id'], unique=False)
    op.create_index('ix_rules_priority', 'rules', ['priority'], unique=False)
    op.create_table('classification_results',
        sa.Column('classification_result_id', sa.UUID(), nullable=False),
        sa.Column('transaction_id', sa.UUID(), nullable=False),
        sa.Column('category_id', sa.Integer(), nullable=False),
        sa.Column('category_name', sa.String(length=255), nullable=False),
        sa.Column('confidence', sa.Float(), nullable=False),
        sa.Column('source', postgresql.ENUM('RULES', 'ML', 'MANUAL', name='classification_source_enum', create_type=False), nullable=False),
        sa.Column('model_version', sa.String(length=255), nullable=True),
        sa.Column('merchant', sa.String(length=255), nullable=True),
        sa.Column('description', sa.String(), nullable=True),
        sa.Column('mcc', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.CheckConstraint('confidence >= 0.0 AND confidence <= 1.0', name='ck_confidence_range'),
        sa.ForeignKeyConstraint(['category_id'], ['categories.category_id'], ),
        sa.PrimaryKeyConstraint('classification_result_id')
    )
    op.create_index('ix_classification_results_source', 'classification_results', ['source'], unique=False)
    op.create_index('ix_classification_results_transaction_id', 'classification_results', ['transaction_id'], unique=True)
    op.create_table('feedback',
        sa.Column('feedback_id', sa.UUID(), nullable=False),
        sa.Column('transaction_id', sa.UUID(), nullable=False),
        sa.Column('correct_category_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=True),
        sa.Column('comment', sa.String(), nullable=True),
        sa.Column('processed', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['correct_category_id'], ['categories.category_id'], ),
        sa.PrimaryKeyConstraint('feedback_id')
    )
    op.create_index('ix_feedback_processed', 'feedback', ['processed'], unique=False)
    op.create_index('ix_feedback_transaction_id', 'feedback', ['transaction_id'], unique=False)
    op.create_table('outbox_events',
        sa.Column('event_id', sa.UUID(), nullable=False),
        sa.Column('topic', sa.String(length=255), nullable=False),
        sa.Column('event_type', sa.String(length=255), nullable=False),
        sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('retry_count', sa.Integer(), nullable=False),
        sa.Column('status', sa.String(length=50), nullable=False),
        sa.Column('last_error', sa.String(length=512), nullable=True),
        sa.CheckConstraint('retry_count >= 0', name='ck_retry_count_non_negative'),
        sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index('ix_outbox_status_created_at', 'outbox_events', ['status', 'created_at'], unique=False)
    op.create_table('training_datasets',
        sa.Column('training_dataset_id', sa.UUID(), nullable=False),
        sa.Column('version', sa.String(length=100), nullable=False),
        sa.Column('file_path', sa.String(length=1024), nullable=False),
        sa.Column('status', postgresql.ENUM('PENDING', 'BUILDING', 'READY', 'FAILED', name='training_dataset_status_enum', create_type=False), nullable=False),
        sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('training_dataset_id')
    )
    op.create_index('ix_training_datasets_status_created', 'training_datasets', ['created_at', 'status'], unique=False, postgresql_where=sa.text("status = 'ready'"))
    op.create_index('ix_training_datasets_version', 'training_datasets', ['version'], unique=True)
    op.execute("""
    INSERT INTO categories (category_id, name, description, keywords) VALUES
    (1, 'Прочее', 'Нераспознанное', ARRAY[]::varchar[]),
    (2, 'Продукты', 'Супермаркеты', ARRAY['pyaterochka','magnit','lenta','auchan','dixy','perekrestok','metro','okey','spar','globus','vkusvill','samokat','sbermarket','krasnoe&beloe','winelab','bristol','azbuka vkusa','supermarket','grocery']),
    (3, 'Кафе и рестораны', 'Общепит', ARRAY['mcdonalds','kfc','burger king','starbucks','dodo','dominospizza','yakitoriya','shokoladnitsa','teremok','subway','tanuki','burger','coffee','restaurant','cafe']),
    (4, 'Одежда и обувь', 'Fashion', ARRAY['zara','hm','uniqlo','lamoda','wildberries','asos','sportmaster','adidas','nike','reebok','rendez-vous','ostin','colins','befree','gloria jeans','mango','reserved','sneakers']),
    (5, 'Электроника', 'Техника', ARRAY['mvideo','eldorado','dns','citilink','restore','samsung','xiaomi','huawei','svyaznoy','megafon retail','mts shop','re-store','technopark']),
    (6, 'Строительство и ремонт', 'Дом', ARRAY['leroy merlin','obi','castorama','hoff','petrovich','ikea','maxidom','stroy','remont']),
    (7, 'Товары для дома', 'Быт', ARRAY['fix price','galamart','posuda','domovoy','togas','kuchenland','uyuterra']),
    (8, 'Красота и уход', 'Косметика', ARRAY['letu','rive gauche','sephora','goldapple','ile de beaute','barbershop','salon','parikmaher','kosmetika','manicure']),
    (9, 'Зоотовары', 'Животные', ARRAY['4lapy','bethoven','petshop','cats&dogs','le murr','zapovednik','zoo']),
    (10, 'Книги и канцелярия', 'Книги', ARRAY['chitai-gorod','labirint','bookvoed','litres','respublica','ozon books','books','knigi']),
    (11, 'Аптеки', 'Лекарства', ARRAY['apteka','rigla','36.6','gorzdrav','planetazdorovo','eapteka','stolichki','vita','pharmacy']),
    (12, 'Медицинские услуги', 'Врачи', ARRAY['invitro','gemotest','helix','medsi','sm-clinic','cmd','dentist','stomatolog','clinic','doctor','meditsina']),
    (13, 'Топливо', 'АЗС', ARRAY['lukoil','gazpromneft','rosneft','bp','shell','tatneft','bashneft','neftmagistral','circle k','teboil','azs','oil']),
    (14, 'Автосервисы', 'ТО', ARRAY['rolf','major','fit service','avtoruss','shinomontazh','car wash','moika','autoservice']),
    (15, 'Автозапчасти', 'Детали', ARRAY['exist','autodoc','emex','kolesa darom','virbac','autoparts','zapchasti']),
    (16, 'Парковки и штрафы', 'Госуслуги', ARRAY['mos.ru','gibdd','shtraf','parking','parkovka','tsodd','ampc']),
    (17, 'Подписки', 'Онлайн сервисы', ARRAY['netflix','spotify','yandex plus','youtube premium','zoom','ivi','okko','kinopoisk','start.ru','amediateka','premier','more.tv']),
    (18, 'Игры', 'Гейминг', ARRAY['steam','playstation','xbox','nintendo','blizzard','gog','epic games','donationalerts','my.games','wargaming']),
    (19, 'Маркетплейсы', 'Универсальные', ARRAY['ozon','wb retail','wildberries','aliexpress','yandex market','kazanexpress','sbermegamarket','lamoda']),
    (20, 'Общественный транспорт', 'Метро/Автобус', ARRAY['mosmetro','troika','strelka','pass','rzd','metro','aeroexpress','trans','transport']),
    (21, 'Такси и каршеринг', 'Такси', ARRAY['yandex taxi','uber','gettaxi','citymobil','delimobil','youdrive','belkacar','citidrive','maxim','indriver','taxi']),
    (22, 'ЖКХ', 'Коммуналка', ARRAY['mosenergosbyt','zhku','epd','kvartplata','gazprom mezhregiongaz','dom.ru','rostelecom','mgts','erc','uk ','tszh']),
    (23, 'Связь', 'Мобильная', ARRAY['mts','beeline','megafon','tele2','yota','tinkoff mobile','sbermobile','skylink']),
    (24, 'Финансы', 'Банки', ARRAY['tinkoff','sberbank','vtb','alfabank','raiffeisen','gazprombank','otkritie','sovcombank','bank','commission']),
    (25, 'Образование', 'Обучение', ARRAY['skyeng','skillbox','geekbrains','netology','coursera','udemy','stepik','study','school','university']),
    (26, 'Развлечения', 'Кино/Театр', ARRAY['kino','cinema','theater','kassir','ticketland','afisha','concert','karofilm','formula kino','theater']),
    (27, 'Спорт', 'Фитнес', ARRAY['world class','x-fit','alex fitness','ddx','spirit','sportmaster','decathlon','fitness','gym']),
    (28, 'Путешествия', 'Туризм', ARRAY['aeroflot','s7','pobeda','utair','ural airlines','turkish airlines','booking','airbnb','aviasales','tutu','onetwotrip','ostrovok','hotel','tour']),
    (29, 'Благотворительность', 'Фонды', ARRAY['podari zhizn','rusfond','wwf','greenpeace','nuzhna pomosh','charity']),
    (30, 'Цветы и подарки', 'Праздник', ARRAY['florist','flowers','flowwow','buket','tsveti'])
    ON CONFLICT (category_id) DO NOTHING;
    """)
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('training_datasets')
    op.drop_table('outbox_events')
    op.drop_table('feedback')
    op.drop_table('classification_results')
    op.drop_table('rules')
    op.drop_table('models')
    op.drop_table('categories')
    op.execute("DROP TYPE training_dataset_status_enum")
    op.execute("DROP TYPE rule_pattern_type_enum")
    op.execute("DROP TYPE classification_source_enum")
    # ### end Alembic commands ###
