"""correct schema

Revision ID: 8bd009546353
Revises: 
Create Date: 2025-12-16 15:04:30.552245+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8bd009546353'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('categoryId', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('keywords', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('categoryId'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ix_categories_keywords_gin', 'categories', ['keywords'], unique=False, postgresql_using='gin')
    op.create_index('ix_categories_name', 'categories', ['name'], unique=False)
    op.create_table('models',
    sa.Column('imodelIdd', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=100), nullable=False),
    sa.Column('path', sa.String(length=1024), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('isActive', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('modelId'),
    sa.UniqueConstraint('version')
    )
    op.create_index('ix_models_active_unique', 'models', ['isActive'], unique=True, postgresql_where=sa.text('isActive IS true'))
    op.create_index('ix_models_createdAt', 'models', [sa.literal_column('createdAt DESC')], unique=False)
    op.create_index('ix_models_version', 'models', ['version'], unique=True)
    op.create_table('training_datasets',
    sa.Column('trainingDatasetId', sa.UUID(), nullable=False),
    sa.Column('version', sa.String(length=100), nullable=False),
    sa.Column('filePath', sa.String(length=1024), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'BUILDING', 'READY', 'FAILED', name='training_dataset_status_enum'), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('trainingDatasetId'),
    sa.UniqueConstraint('version')
    )
    op.create_index('ix_training_datasets_status_created', 'training_datasets', ['createdAt', 'status'], unique=False, postgresql_where=sa.text("status = 'READY'"))
    op.create_index('ix_training_datasets_version', 'training_datasets', ['version'], unique=True)
    op.create_table('classification_results',
    sa.Column('classificationResultId', sa.UUID(), nullable=False),
    sa.Column('transactionId', sa.UUID(), nullable=False),
    sa.Column('categoryId', sa.Integer(), nullable=False),
    sa.Column('categoryName', sa.String(length=255), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source', sa.Enum('RULES', 'ML', 'MANUAL', name='classification_source_enum'), nullable=False),
    sa.Column('modelVersion', sa.String(length=255), nullable=True),
    sa.Column('merchant', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('mcc', sa.Integer(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['categoryId'], ['categories.categoryId'], ),
    sa.PrimaryKeyConstraint('classificationResultId'),
    sa.UniqueConstraint('transactionId')
    )
    op.create_index('ix_classification_results_source', 'classification_results', ['source'], unique=False)
    op.create_index('ix_classification_results_transactionId', 'classification_results', ['transactionId'], unique=True)
    op.create_table('feedback',
    sa.Column('feedbackId', sa.UUID(), nullable=False),
    sa.Column('transactionId', sa.UUID(), nullable=False),
    sa.Column('correctCategoryId', sa.Integer(), nullable=False),
    sa.Column('userId', sa.UUID(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['correctCategoryId'], ['categories.categoryId'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_feedback_processed', 'feedback', ['processed'], unique=False)
    op.create_index('ix_feedback_transactionId', 'feedback', ['transactionId'], unique=False)
    op.create_table('rules',
    sa.Column('ruleId', sa.UUID(), nullable=False),
    sa.Column('categoryId', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('pattern', sa.String(), nullable=False),
    sa.Column('patternType', sa.Enum('REGEX', 'CONTAINS', 'MCC', 'EXACT', name='rule_pattern_type_enum'), nullable=False),
    sa.Column('mcc', sa.Integer(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['categoryId'], ['categories.categoryId'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ruleId')
    )
    op.create_index('ix_rules_categoryId', 'rules', ['categoryId'], unique=False)
    op.create_index('ix_rules_priority', 'rules', ['priority'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_rules_priority', table_name='rules')
    op.drop_index('ix_rules_categoryId', table_name='rules')
    op.drop_table('rules')
    op.drop_index('ix_feedback_transactionId', table_name='feedback')
    op.drop_index('ix_feedback_processed', table_name='feedback')
    op.drop_table('feedback')
    op.drop_index('ix_classification_results_transactionId', table_name='classification_results')
    op.drop_index('ix_classification_results_source', table_name='classification_results')
    op.drop_table('classification_results')
    op.drop_index('ix_training_datasets_version', table_name='training_datasets')
    op.drop_index('ix_training_datasets_status_created', table_name='training_datasets', postgresql_where=sa.text("status = 'READY'"))
    op.drop_table('training_datasets')
    op.drop_index('ix_models_version', table_name='models')
    op.drop_index('ix_models_createdAt', table_name='models')
    op.drop_index('ix_models_active_unique', table_name='models', postgresql_where=sa.text('isActive IS true'))
    op.drop_table('models')
    op.drop_index('ix_categories_name', table_name='categories')
    op.drop_index('ix_categories_keywords_gin', table_name='categories', postgresql_using='gin')
    op.drop_table('categories')
    # ### end Alembic commands ###
